export var departments = [
  { name: 'Academy for Classical Acting', acronym: 'ACA' },
  { name: 'Accountancy', acronym: 'ACCY' },
  { name: 'Africana Studies', acronym: 'AFST' },
  { name: 'American Studies', acronym: 'AMST' },
  { name: 'Anatomy and Regenerative Biology', acronym: 'ANAT' },
  { name: 'Anthropology', acronym: 'ANTH' },
  { name: 'Applied Science', acronym: 'APSC' },
  { name: 'Arabic', acronym: 'ARAB' },
  { name: 'Art History', acronym: 'AH' },
  { name: 'Art Therapy', acronym: 'ARTH' },
  { name: 'Astronomy', acronym: 'ASTR' },
  { name: 'Biochemistry', acronym: 'BIOC' },
  { name: 'Biological Sciences', acronym: 'BISC' },
  { name: 'Biomedical Engineering', acronym: 'BME' },
  { name: 'Biomedical Sciences', acronym: 'BMSC' },
  { name: 'Biostatistics', acronym: 'BIOS' },
  { name: 'Business Administration', acronym: 'BADM' },
  { name: 'Chemistry', acronym: 'CHEM' },
  { name: 'Chinese', acronym: 'CHIN' },
  { name: 'Civil Engineering', acronym: 'CE' },
  { name: 'Classical Studies', acronym: 'CLAS' },
  { name: 'Clinical Management and Leadership', acronym: 'CML' },
  { name: 'Clinical Research Admin', acronym: 'CRA' },
  { name: 'College of Professional Studies', acronym: 'CPS' },
  { name: 'Columbian College', acronym: 'CCAS' },
  { name: 'Communication', acronym: 'COMM' },
  { name: 'Computer Science', acronym: 'CSCI' },
  { name: 'Corcoran Art and the Book', acronym: 'CBK' },
  { name: 'Corcoran Art Education', acronym: 'CED' },
  { name: 'Corcoran Art History', acronym: 'CAH' },
  { name: 'Corcoran Arts and Humanities', acronym: 'CAS' },
  { name: 'Corcoran Ceramics', acronym: 'CCR' },
  { name: 'Corcoran Continuing Education', acronym: 'CCE' },
  { name: 'Corcoran Decorative Arts and Design', acronym: 'CDAD' },
  { name: 'Corcoran Design', acronym: 'CDE' },
  { name: 'Corcoran Digital Media Design', acronym: 'CDM' },
  { name: 'Corcoran Exhibition Design', acronym: 'CEX' },
  { name: 'Corcoran Fine Art', acronym: 'CFA' },
  { name: 'Corcoran First Year Foundation', acronym: 'CFN' },
  { name: 'Corcoran Graphic Design', acronym: 'CGD' },
  { name: 'Corcoran Interior Design', acronym: 'CID' },
  { name: 'Corcoran Photography', acronym: 'CPH' },
  { name: 'Corcoran Photojournalism', acronym: 'CPJ' },
  { name: 'Corcoran Printmaking', acronym: 'CPR' },
  { name: 'Corcoran Sculpture', acronym: 'CSL' },
  { name: 'Counseling', acronym: 'CNSL' },
  { name: 'Curriculum and Pedagogy', acronym: 'CPED' },
  { name: 'Data Science', acronym: 'DATS' },
  { name: 'Decision Sciences', acronym: 'DNSC' },
  { name: 'East Asian Language and Literature', acronym: 'EALL' },
  { name: 'Economics', acronym: 'ECON' },
  { name: 'Educational Leadership', acronym: 'EDUC' },
  { name: 'Electrical and Computer Engring', acronym: 'ECE' },
  { name: 'Emergency Health Services', acronym: 'EHS' },
  { name: 'Engineering Management and Systems Engineering', acronym: 'EMSE' },
  { name: 'English', acronym: 'ENGL' },
  { name: 'English for Academic Purposes', acronym: 'EAP' },
  { name: 'Environmental Resource Policy', acronym: 'ENRP' },
  { name: 'Environmental Studies', acronym: 'ENVR' },
  { name: 'Epidemiology', acronym: 'EPID' },
  { name: 'Exercise and Nutrition Sciences', acronym: 'EXNS' },
  { name: 'Film Studies', acronym: 'FILM' },
  { name: 'Finance', acronym: 'FINA' },
  { name: 'Fine Arts', acronym: 'FA' },
  { name: 'Forensic Psychology', acronym: 'FORP' },
  { name: 'Forensic Sciences', acronym: 'FORS' },
  { name: 'French', acronym: 'FREN' },
  { name: 'Geography', acronym: 'GEOG' },
  { name: 'Geology', acronym: 'GEOL' },
  { name: 'Germanic Language and Literature', acronym: 'GER' },
  { name: 'Government Contracts', acronym: 'GCON' },
  { name: 'Greek', acronym: 'GREK' },
  { name: 'GWTeach', acronym: 'GTCH' },
  { name: 'Health Care Quality', acronym: 'HCQ' },
  { name: 'Health Care Science', acronym: 'HCS' },
  { name: 'Health Sciences Programs', acronym: 'HSCI' },
  { name: 'Health Services Management and Leadership', acronym: 'HSML' },
  { name: 'Health and Wellness', acronym: 'HLWL' },
  { name: 'Hebrew', acronym: 'HEBR' },
  { name: 'History', acronym: 'HIST' },
  { name: 'Hominid Paleobiology', acronym: 'HOMP' },
  { name: 'Honors', acronym: 'HONR' },
  { name: 'Human Development', acronym: 'HDEV' },
  { name: 'Human Organizational Learning', acronym: 'HOL' },
  { name: 'Human Services and Social Justice', acronym: 'HSSJ' },
  { name: 'Informatics', acronym: 'INFR' },
  { name: 'Information Systems Technology Management', acronym: 'ISTM' },
  { name: 'Integrative Medicine', acronym: 'INTM' },
  { name: 'Interior Architecture', acronym: 'IA' },
  { name: 'International Affairs', acronym: 'IAFF' },
  { name: 'International Business', acronym: 'IBUS' },
  { name: 'Italian', acronym: 'ITAL' },
  { name: 'Japanese', acronym: 'JAPN' },
  { name: 'Judaic Studies', acronym: 'JSTD' },
  { name: 'Korean', acronym: 'KOR' },
  { name: 'Latin', acronym: 'LATN' },
  { name: 'Law', acronym: 'LAW' },
  { name: 'Legislative Affairs', acronym: 'LGAF' },
  { name: 'Lifestyle, acronym: Sport, acronym: and Physical Activity', acronym: 'LSPA' },
  { name: 'Linguistics', acronym: 'LING' },
  { name: 'Management', acronym: 'MGT' },
  { name: 'Marketing', acronym: 'MKTG' },
  { name: 'Master of Business Administration', acronym: 'MBAD' },
  { name: 'Mathematics', acronym: 'MATH' },
  { name: 'Mechanical and Aerospace Engineering', acronym: 'MAE' },
  { name: 'Medical Laboratory Science', acronym: 'MLS' },
  { name: 'Microbiology, acronym: Immunology, acronym: and Tropical Medicine', acronym: 'MICR' },
  { name: 'Molecular Medicine', acronym: 'MMED' },
  { name: 'Museum Studies', acronym: 'MSTD' },
  { name: 'Music', acronym: 'MUS' },
  { name: 'Naval Science', acronym: 'NSC' },
  { name: 'Nursing', acronym: 'NURS' },
  { name: 'Organizational Sciences', acronym: 'ORSC' },
  { name: 'Patent Practice', acronym: 'PATN' },
  { name: 'Peace Studies', acronym: 'PSTD' },
  { name: 'Persian', acronym: 'PERS' },
  { name: 'Pharmacogenomics', acronym: 'PHRG' },
  { name: 'Pharmacology', acronym: 'PHAR' },
  { name: 'Philosophy', acronym: 'PHIL' },
  { name: 'Physical Therapy', acronym: 'PT' },
  { name: 'Physician Assistant', acronym: 'PA' },
  { name: 'Physics', acronym: 'PHYS' },
  { name: 'Physiology', acronym: 'PHYL' },
  { name: 'Political Management', acronym: 'PMGT' },
  { name: 'Political Psychology', acronym: 'PPSY' },
  { name: 'Political Science', acronym: 'PSC' },
  { name: 'Portuguese', acronym: 'PORT' },
  { name: 'Professional Studies Advocacy Global Environment', acronym: 'PSAD' },
  { name: 'Professional Studies Cybersecurity Strategy and Information Management', acronym: 'PSCS' },
  { name: 'Professional Studies Healthcare Corporate Complaince', acronym: 'PSHC' },
  { name: 'Professional Studies Homeland Security', acronym: 'PSHS' },
  { name: 'Professional Studies Integrated Information, acronym: Science, acronym: and Technology', acronym: 'PSIS' },
  { name: 'Professional Studies Landscape Design', acronym: 'PSLD' },
  { name: 'Professional Studies Law Firm Management', acronym: 'PSLM' },
  { name: 'Professional Studies Molecular Biology', acronym: 'PSMB' },
  { name: 'Professional Studies Paralegal Studies', acronym: 'PSLX' },
  { name: 'Professional Studies Public Leadership', acronym: 'PSPL' },
  { name: 'Professional Studies Public Relations', acronym: 'PSPR' },
  { name: 'Professional Studies Publishing', acronym: 'PSPB' },
  { name: 'Professional Studies Urban Sustainability', acronym: 'PSUS' },
  { name: 'Professional Studies Security and Safety Leadership', acronym: 'PSSL' },
  { name: 'Professional Psychology', acronym: 'PSYD' },
  { name: 'Psychology', acronym: 'PSYC' },
  { name: 'Public Health', acronym: 'PUBH' },
  { name: 'Public Policy and Public Admin', acronym: 'PPPA' },
  { name: 'Regulatory Affairs', acronym: 'RAFF' },
  { name: 'Religion', acronym: 'REL' },
  { name: 'School of Engineering and Applied Science', acronym: 'SEAS' },
  { name: 'School of Media and Public Affairs', acronym: 'SMPA' },
  { name: 'Slavic Languages and Literature', acronym: 'SLAV' },
  { name: 'Sociology', acronym: 'SOC' },
  { name: 'Spanish', acronym: 'SPAN' },
  { name: 'Special Education', acronym: 'SPED' },
  { name: 'Speech and Hearing Science', acronym: 'SPHR' },
  { name: 'Statistics', acronym: 'STAT' },
  { name: 'Strategic Management and Public Policy', acronym: 'SMPP' },
  { name: 'Sustainability', acronym: 'SUST' },
  { name: 'Theatre and Dance', acronym: 'TRDA' },
  { name: 'Tourism Studies', acronym: 'TSTD' },
  { name: 'Turkish', acronym: 'TURK' },
  { name: 'University Writing', acronym: 'UW' },
  { name: 'Vietnamese', acronym: 'VIET' },
  { name: 'Women and Leadership Program', acronym: 'WLP' },
  { name: 'Women\'s, Gender, and Sexuality Studies', acronym: 'WGSS' },
  { name: 'Yiddish', acronym: 'YDSH' }
]
